### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Daniel-Low** [IRSgov/IDES-Data-Preparation-Java#1]
I have followed the instructions in the post to the letter with the exception of using jre1.8.0_45 instead of jre1.8.0_40 (as jre1.8.0_40 is no longer available on Oracle website). The following below are the list of errors in my program. What could be the cause of this?

Thank you and best regards,
Daniel

Description	Resource	Path	Location	Type
Access restriction: The constructor 'IgnoreAllErrorHandler()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 116	Java Problem
Access restriction: The constructor 'IgnoreAllErrorHandler()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 161	Java Problem
Access restriction: The constructor 'IgnoreAllErrorHandler()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 163	Java Problem
Access restriction: The constructor 'XMLGregorianCalendarImpl(GregorianCalendar)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAPackager.java	/IDESDataPreparation/src/fatca	line 357	Java Problem
Access restriction: The method 'Base64.encode(byte[])' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 138	Java Problem
Access restriction: The method 'Base64.encode(byte[])' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 426	Java Problem
Access restriction: The method 'Base64.encode(byte[])' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	UtilShared.java	/IDESDataPreparation/src/fatca	line 168	Java Problem
Access restriction: The method 'Base64.encode(byte[])' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	UtilShared.java	/IDESDataPreparation/src/fatca	line 169	Java Problem
Access restriction: The method 'Canonicalizer.canonicalize(byte[])' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 424	Java Problem
Access restriction: The method 'Canonicalizer.canonicalizeSubtree(Node)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 274	Java Problem
Access restriction: The method 'Canonicalizer.canonicalizeSubtree(Node)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 278	Java Problem
Access restriction: The method 'Canonicalizer.canonicalizeSubtree(Node)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 287	Java Problem
Access restriction: The method 'Canonicalizer.canonicalizeSubtree(Node)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 289	Java Problem
Access restriction: The method 'Canonicalizer.getInstance(String)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 110	Java Problem
Access restriction: The method 'Canonicalizer.getInstance(String)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 159	Java Problem
Access restriction: The method 'Canonicalizer.getInstance(String)' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 421	Java Problem
Access restriction: The method 'Init.init()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 104	Java Problem
Access restriction: The method 'Init.init()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 420	Java Problem
Access restriction: The method 'Init.isInitialized()' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 419	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 51	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 138	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 426	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	UtilShared.java	/IDESDataPreparation/src/fatca	line 29	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	UtilShared.java	/IDESDataPreparation/src/fatca	line 168	Java Problem
Access restriction: The type 'Base64' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	UtilShared.java	/IDESDataPreparation/src/fatca	line 169	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 50	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 94	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 110	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 159	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 159	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 252	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 421	Java Problem
Access restriction: The type 'Canonicalizer' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 421	Java Problem
Access restriction: The type 'IgnoreAllErrorHandler' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 52	Java Problem
Access restriction: The type 'IgnoreAllErrorHandler' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 116	Java Problem
Access restriction: The type 'IgnoreAllErrorHandler' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 161	Java Problem
Access restriction: The type 'IgnoreAllErrorHandler' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 163	Java Problem
Access restriction: The type 'Init' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 49	Java Problem
Access restriction: The type 'Init' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 104	Java Problem
Access restriction: The type 'Init' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 419	Java Problem
Access restriction: The type 'Init' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAXmlSigner.java	/IDESDataPreparation/src/fatca	line 420	Java Problem
Access restriction: The type 'XMLGregorianCalendarImpl' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAPackager.java	/IDESDataPreparation/src/fatca	line 44	Java Problem
Access restriction: The type 'XMLGregorianCalendarImpl' is not API (restriction on required library 'C:\Program Files\Java\jre1.8.0_45\lib\rt.jar')	FATCAPackager.java	/IDESDataPreparation/src/fatca	line 357	Java Problem

**Comment by DanielCrouch** [comment]
You should still be able to get the _40 version. There is an archives option at the bottom of the download page that has all their older versions. So as they release updates, they move the older JREs over there, but you can still access them. See if this gets you there: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jre-8u40-oth-JPR.

The code was built using an older 1.7 version of the JRE. When I created the walkthrough, I used the newer 1.8 JRE. I had a similar issue to what you stated when I used it in Eclipse. In the JRE settings, it was using the "Use an execution environment JRE" radio button option and it was set to JavaSE-1.8. I had to switch that to the "Use a project specific JRE" with the jre1.8.0_40 selected. That took care of the issue and my huge list of errors went away. You can see those radio button options on the second screen shot in the walkthrough. I think for an existing project, you can go to Project --> Properties, then select Java Build Path, the Libraries tab, highlight the JRE System option and hit the Edit button then you have the Execution Environment and Alternate JRE and you should be able to manually select the Alternate JRE version to use. For example, when I do that, it shows the _40 version for mine.

**Comment by Daniel-Low** [comment]
Thank you DanielCrouch. Implemented as suggested but I am getting a new list of errors:

log4j:WARN No appenders could be found for logger (fatca.FATCAXmlSigner).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at fatca.FATCAPackager.aes(FATCAPackager.java:84)
	at fatca.FATCAPackager.encrypt(FATCAPackager.java:134)
	at fatca.FATCAPackager.encrypt(FATCAPackager.java:116)
	at fatca.FATCAPackager.createPkgWithApprover(FATCAPackager.java:460)
	at fatca.FATCAPackager.createPkg(FATCAPackager.java:408)
	at fatca.TestMain.main(TestMain.java:53)
Exception in thread "main" java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at fatca.FATCAPackager.aes(FATCAPackager.java:84)
	at fatca.FATCAPackager.encrypt(FATCAPackager.java:134)
	at fatca.FATCAPackager.encrypt(FATCAPackager.java:116)
	at fatca.FATCAPackager.createPkgWithApprover(FATCAPackager.java:460)
	at fatca.FATCAPackager.createPkg(FATCAPackager.java:408)
	at fatca.TestMain.main(TestMain.java:53)

**Comment by Roriro** [comment]
Did you compile with Java 8?

Regards

**Comment by DanielCrouch** [comment]
You may want to look at this article. It could be one of the Java security or policy files that is missing or needs to be updated. I haven't seen that happen with the Java app yet.

http://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

**Comment by Roriro** [comment]
This solution work for me. http://www.javacirecep.com/java-security/java-java-security-invalidkeyexception-illegal-key-size-or-default-parameters/ <http://www.javacirecep.com/java-security/java-java-security-invalidkeyexception-illegal-key-size-or-default-parameters/>

**Comment by ChtiSuisse** [comment]
Dear all,
Not sure if that helps but under JDK7 we did our own encrpytion (very close to this one)
We need (bouncyclastle libs) :
bcprov-jdk15on-1.51.jar and    bcpkix-jdk15on-1.51.jar
to be put in jre7\lib\ext
And edit jre7\lib\security\java.security
To add bouncyCastle to the security providers
security.provider.1=sun.security.provider.Sun
    security.provider.2=org.bouncycastle.jce.provider.BouncyCastleProvider
    security.provider.3=sun.security.rsa.SunRsaSign
    security.provider.4=sun.security.ec.SunEC
    security.provider.5=com.sun.net.ssl.internal.ssl.Provider
    security.provider.6=com.sun.crypto.provider.SunJCE
    security.provider.7=sun.security.jgss.SunProvider
    security.provider.8=com.sun.security.sasl.Provider
    security.provider.9=org.jcp.xml.dsig.internal.dom.XMLDSigRI
    security.provider.10=sun.security.smartcardio.SunPCSC
    security.provider.11=sun.security.mscapi.SunMSCAPI

Our code works and we have already sent data to IDES (successfully)

Regards

Chris

**Comment by Daniel-Low** [comment]
Thank you all for your helpful suggestions. Have managed to make the program run.

Best regards,
Daniel

**Comment by Huguex** [comment]
Tuve el mismo error y fue un problema de políticas.
Buen aporte.
