### ISSUE TITLE
Problem with message digest

### ISSUE THREAD

**Issue by emacionm** [IRSgov/IDES-Data-Preparation-Java#2]
Hi there

I'm using the code provided here to create the FATCA data packages. 

When testing in IDES (test env) I'm getting notifications back that say that signature validation failed.

I've run signature validation using verifySignatureDOM in UtilShared and there seems to be a problem with the digest.
```
DEBUG UtilShared - Signature core validation false
DEBUG UtilShared - SignatureValue validation status: true
DEBUG UtilShared - ref[0] validity status: false
DEBUG UtilShared - ref.getURI()=#FATCA
DEBUG UtilShared - ref.getCalculatedDigestValue()=tr7qH8aWGvFVYVy89dasvP3tIlZDGYxcjAyJlq0JNYo=
DEBUG UtilShared - ref.getDigestValue()=kfxyLnCUPi24RVQUgNbKP/RHcvxxP69ZlLwj6sUWCEU=

```
The calculated (ie expected) digest and actual digest don't seem to match.

Has anyone else seen this issue? I've tried a variety of Canonicalization settings (none/ CanonicalizationMethod.INCLUSIVE/ CanonicalizationMethod.EXCLUSIVE) and no joy.

I'm also a bit confused by this code in the FATCAXMLSigner class
```java
protected ArrayList<String> xmlChunkToCalcDigest = new ArrayList<String>(Arrays.asList(
			"MessageSpec", "ReportingFI", "Sponsor", "Intermediary", "AccountReport", "PoolReport"));
```

Why does the code only use those tags to calculate the digest (maybe I'm misunderstanding this), and if so how is the validation in the verify signature supposed to be aware of this?

thanks
Eoin

**Comment by DanielCrouch** [comment]
Do you have a test XML file that causes the error that you can share that we could look at? If so, please send it to lbi.fatca.ides@irs.gov. Please add something like "Github" to the subject line for it. I will see if we have any code updates to publish for this as well.

**Comment by emacionm** [comment]
Hi Daniel 

Thanks very much - I've sent now

**Comment by DanielCrouch** [comment]
Thanks, I have someone looking at them now.

**Comment by DanielCrouch** [comment]
Here is a note I received back. Sounds like if you clear up the blank space after the last tag, it should be ok.

There is a newline after the xml last tag is causing incorrect signature as our code stops reading beyond last tag. We will see if this can be fixed. Meanwhile they user can do either:
-	Remove newline (and all whitespace characters) after last tag
-	If file/xml is not large, use signDOM() instead of signStreaming()

**Comment by emacionm** [comment]
Thanks Daniel,

I'll give that a go and report back!

**Comment by emacionm** [comment]
Hi Daniel

I've decided to go with SignDOM() method as seemed to be still getting some weird behaviour in the streaming version. Getting actual validation messages back via test IDES now. Thanks for help

**Comment by DanielCrouch** [comment]
I do have an update to publish that will take care of the blank space issue as well, so it will take care of that situation.
