### ISSUE TITLE
Question about creating "000000.00000.TA.124_0_Payload.xml.signed" file (from example)

### ISSUE THREAD

**Issue by OldHook** [IRSgov/IDES-Data-Preparation-Java#3]
TestMain.java

After line 48 after "m.signer.signStreaming(canadaXml, signedCanadaXml, m.canadaSigKey, m.canadaPubCert);" created file "000000.00000.TA.124_0_Payload.xml.signed"

After line 49 after "m.signer.signDOM(canadaXml, signedCanadaXml, m.canadaSigKey, m.canadaPubCert);" created new version of "000000.00000.TA.124_0_Payload.xml.signed" file. Previuos file is overwritten.

These *.xml.signed files are different by digests and "Transforms" section.
What version of *.xml.signed file is correct? First or second?

Vladimir.

P.S. Sorry for my English.

**Comment by OldHook** [comment]
Anybody?

**Comment by DanielCrouch** [comment]
The streaming and DOM versions should both work fine. One was intended for very large files and the other is for smaller files. I do have a newer version of the Signer class that will be posted very shortly though.

**Comment by OldHook** [comment]
Thank you for reply.
